name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
<<<<<<< HEAD
        python-version: [3.11, 3.12]
=======
        python-version: [3.12, 3.13]
>>>>>>> d4e61c19a5fc5e3dcde40ce4ebcf900f98bba6ef

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        cd src
        python -m pytest addition.py
